server:
  port: 8888
spring:
  application:
    name: servertwo
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokders: localhost:9092
          zkNodes: localhost:2181